# Generated by Django 3.2.7 on 2023-06-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barangay_name', models.CharField(choices=[('Alegria', 'Alegria'), ('Bagacay', 'Bagacay'), ('Baluntay', 'Baluntay'), ('Datal Anggas', 'Datal Anggas'), ('Domolok', 'Domolok'), ('Kawas', 'Kawas'), ('Ladol', 'Ladol'), ('Maribulan', 'Maribulan'), ('Pag-Asa', 'Pag-Asa'), ('Paraiso', 'Paraiso'), ('Poblacion', 'Poblacion'), ('Spring', 'Spring'), ('Tokawal', 'Tokawal')], default='Alegria', max_length=100, unique=True, verbose_name='Barangay Name')),
                ('barangay_img', models.ImageField(blank=True, default='default.jpg', upload_to='history_imgs', verbose_name='Image')),
                ('barangay_info', models.TextField(blank=True, verbose_name='History')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'ordering': ['barangay_name'],
            },
        ),
        migrations.CreateModel(
            name='Hotlines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(blank=True, help_text='TeleComm Companies (i.e., Smart, Globe) Channel Type (i.e., Radio Frequencies,Landline,Department)', max_length=20, null=True, verbose_name='Channel - Medium Type')),
                ('contact_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Number')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliary.contacts')),
            ],
            options={
                'verbose_name': 'Hotline',
                'verbose_name_plural': 'Hotlines',
                'ordering': ['-contacts'],
            },
        ),
        migrations.CreateModel(
            name='GeoHazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geohazard_img', models.ImageField(blank=True, default='default.jpg', upload_to='history_imgs', verbose_name='Image')),
                ('date_published', models.CharField(blank=True, max_length=50, null=True)),
                ('geohazard_info', models.TextField(verbose_name='Description')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geohazards', to='auxiliary.history')),
            ],
            options={
                'verbose_name': 'GeoHazard',
                'verbose_name_plural': 'GeoHazards',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purok_name', models.CharField(max_length=50, verbose_name='Purok Name')),
                ('purok_coordinates', models.CharField(default='Not Specified', max_length=100, verbose_name='Coordinates')),
                ('landslide_rating', models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('LOW-MODERATE', 'LOW-MODERATE'), ('MODERATE-HIGH', 'MODERATE-HIGH'), ('LOW(High Near Rivers)', 'LOW(High Near Rivers)'), ('LOW(H/M Near Rivers)', 'LOW(H/M Near Rivers)'), ('MODERATE(High Near Rivers)', 'MODERATE(High Near Rivers)'), ('LOW(High On Slopes)', 'LOW(High On Slopes)'), ('MODERATE(High On Slopes)', 'MODERATE(High On Slopes)'), ('LOW(H/M On Slopes)', 'LOW(H/M On Slopes)'), ('LOW(High Near Creeks)', 'LOW(High Near Creeks)'), ('LOW(Moderate Near Creeks)', 'LOW(Moderate Near Creeks)'), ('MODERATE(High Near Creeks)', 'MODERATE(High Near Creeks)'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Landslide Rating')),
                ('flood_rating', models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('LOW-MODERATE', 'LOW-MODERATE'), ('MODERATE-HIGH', 'MODERATE-HIGH'), ('LOW(High Near Rivers)', 'LOW(High Near Rivers)'), ('LOW(H/M Near Rivers)', 'LOW(H/M Near Rivers)'), ('MODERATE(High Near Rivers)', 'MODERATE(High Near Rivers)'), ('LOW(High On Slopes)', 'LOW(High On Slopes)'), ('MODERATE(High On Slopes)', 'MODERATE(High On Slopes)'), ('LOW(H/M On Slopes)', 'LOW(H/M On Slopes)'), ('LOW(High Near Creeks)', 'LOW(High Near Creeks)'), ('LOW(Moderate Near Creeks)', 'LOW(Moderate Near Creeks)'), ('MODERATE(High Near Creeks)', 'MODERATE(High Near Creeks)'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Flood Rating')),
                ('recommendation', models.TextField(default='No data available')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='auxiliary.history')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Image (Optional)')),
                ('content', models.TextField(help_text="Please make sure to keep the content 'concise' as possible.", verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date_posted'],
                'unique_together': {('title', 'content')},
            },
        ),
    ]
