# Generated by Django 3.2.7 on 2023-07-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['purok_name'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
    ]
