# Generated by Django 3.2.7 on 2023-07-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestpost',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Guest Post', 'verbose_name_plural': 'Guest Posts'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
