# Generated by Django 3.2.7 on 2023-06-30 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evac_Centers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Bagacay Gym', 'Bagacay Gym'), ('Alabel Central Elem. School', 'Alabel Central Elem. School'), ('Municipal Gym', 'Municipal Gym'), ('Alegria Covered Court', 'Alegria Covered Court'), ('Purok Kawayan (Bagacay)', 'Purok Kawayan (Bagacay)'), ('Purok 1 (Baluntay)', 'Purok 1 (Baluntay)')], max_length=100, unique=True)),
                ('location', models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(default='default.jpg', upload_to='evac_center_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Evacuation Center',
                'verbose_name_plural': 'Evacuation Centers',
            },
        ),
        migrations.CreateModel(
            name='Warning_Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('location', models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('info', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='default.jpg', upload_to='device_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Warning Device',
                'verbose_name_plural': 'Warning Devices',
            },
        ),
        migrations.CreateModel(
            name='Warning_Signs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sign Name')),
                ('location', models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(default='default.jpg', upload_to='sign_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Warning Sign',
                'verbose_name_plural': 'Warning Signs',
            },
        ),
    ]
