# Generated by Django 3.2.7 on 2023-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evac_centers',
            name='name',
            field=models.CharField(choices=[('Bagacay Gym', 'Bagacay Gym'), ('Purok 1 (Baluntay)', 'Purok 1 (Baluntay)'), ('Municipal Gym', 'Municipal Gym'), ('Alegria Covered Court', 'Alegria Covered Court'), ('Purok Kawayan (Bagacay)', 'Purok Kawayan (Bagacay)'), ('Alabel Central Elem. School', 'Alabel Central Elem. School')], max_length=100, unique=True),
        ),
    ]
