# Generated by Django 3.2.7 on 2023-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_auxiliary', '0003_alter_evac_centers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evac_centers',
            name='name',
            field=models.CharField(choices=[('Municipal Gym', 'Municipal Gym'), ('Spring Gym', 'Spring Gym'), ('Datal Anggas Gym', 'Datal Anggas Gym'), ('Alabel Central Elem. School', 'Alabel Central Elem. School'), ('Purok 1 (Baluntay)', 'Purok 1 (Baluntay)'), ('Paraiso Gym', 'Paraiso Gym'), ('Alegria Covered Court', 'Alegria Covered Court'), ('Domolok Gym', 'Domolok Gym'), ('Purok Kawayan (Bagacay)', 'Purok Kawayan (Bagacay)'), ('Maribulan Gym', 'Maribulan Gym'), ('Baluntay Gym', 'Baluntay Gym'), ('Kawas Gymnasium', 'Kawas Gymnasium'), ('Pag-Asa Gymnasium', 'Pag-Asa Gymnasium'), ('Tokawal Gym', 'Tokawal Gym'), ('Bagacay Gym', 'Bagacay Gym')], max_length=100, unique=True),
        ),
    ]
